/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package sistemagestionempleadosform.FuncGerente;

import java.util.LinkedList;
import sistemagestionempleadosform.Clasess.Empleados;


/**
 *
 * @author USUARIO
 */
public class ContEmp extends javax.swing.JFrame {
    
    public static LinkedList contenedor = new LinkedList();
    public int buscar;
    
    /**
     * Creates new form ContEmp
     */
    public ContEmp() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Datos = new javax.swing.JLabel();
        NomEmp = new javax.swing.JLabel();
        IDEmp = new javax.swing.JLabel();
        SalarEmp = new javax.swing.JLabel();
        TBIDEmp = new javax.swing.JTextField();
        TBSalarEmp = new javax.swing.JTextField();
        btnGuardar = new javax.swing.JButton();
        TBNomEmp = new javax.swing.JTextField();
        btnBack = new javax.swing.JButton();
        btnMostEmp = new javax.swing.JButton();
        TBDepEmp = new javax.swing.JTextField();
        DepEmp = new javax.swing.JLabel();
        btnModDat = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Datos.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        Datos.setText("Complete los datos del registro");

        NomEmp.setFont(new java.awt.Font("Book Antiqua", 0, 14)); // NOI18N
        NomEmp.setText("Nombre del empleado:");

        IDEmp.setFont(new java.awt.Font("Book Antiqua", 0, 14)); // NOI18N
        IDEmp.setText("ID del empleado:");

        SalarEmp.setFont(new java.awt.Font("Book Antiqua", 0, 14)); // NOI18N
        SalarEmp.setText("Salario del empleado:");

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        TBNomEmp.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TBNomEmpKeyTyped(evt);
            }
        });

        btnBack.setText("Regresar");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        btnMostEmp.setText("Ver empleados");
        btnMostEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostEmpActionPerformed(evt);
            }
        });

        DepEmp.setFont(new java.awt.Font("Book Antiqua", 0, 14)); // NOI18N
        DepEmp.setText("Departamento del empleado:");

        btnModDat.setText("Modificar");
        btnModDat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModDatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addComponent(Datos))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(IDEmp)
                            .addComponent(SalarEmp)
                            .addComponent(NomEmp)
                            .addComponent(DepEmp))
                        .addGap(51, 51, 51)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(TBIDEmp)
                            .addComponent(TBSalarEmp)
                            .addComponent(TBDepEmp)
                            .addComponent(TBNomEmp, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnMostEmp))
                        .addGap(104, 104, 104)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnGuardar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnModDat, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(49, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(Datos)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NomEmp)
                    .addComponent(TBNomEmp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(IDEmp)
                    .addComponent(TBIDEmp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SalarEmp)
                    .addComponent(TBSalarEmp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DepEmp)
                    .addComponent(TBDepEmp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardar)
                    .addComponent(btnMostEmp))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBack)
                    .addComponent(btnModDat))
                .addContainerGap(70, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed

        String nombre = TBNomEmp.getText();
        String ID = TBIDEmp.getText();
        String Salario = TBSalarEmp.getText();
        String Departamento = TBDepEmp.getText();
        
        Empleados claseEmpleados = new Empleados(nombre, ID, Salario, Departamento);
        contenedor.add(claseEmpleados);
        
        TBNomEmp.setText("");
        TBIDEmp.setText("");
        TBSalarEmp.setText("");
        TBDepEmp.setText("");
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        MenuGer Malaver = new MenuGer();
        Malaver.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnMostEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostEmpActionPerformed
        VerEmp Jesus = new VerEmp();
        Jesus.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnMostEmpActionPerformed

    private void TBNomEmpKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TBNomEmpKeyTyped
        int press = evt.getKeyChar();
        if(press == 10){
            String IDEncontrado = TBIDEmp.getText().trim();
            Empleados a;
            for (int i = 0 ; i < contenedor.size() ; i++){
                a = (Empleados)contenedor.get(i);
                if (IDEncontrado.equalsIgnoreCase(a.getID())){
                    TBNomEmp.setText(a.getNombre());
                    TBSalarEmp.setText(a.getSalario());
                    TBDepEmp.setText(a.getDepartamento());
                    buscar = i;
                    break;
                }
            }
        }
    }//GEN-LAST:event_TBNomEmpKeyTyped

    private void btnModDatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModDatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnModDatActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Datos;
    private javax.swing.JLabel DepEmp;
    private javax.swing.JLabel IDEmp;
    private javax.swing.JLabel NomEmp;
    private javax.swing.JLabel SalarEmp;
    private javax.swing.JTextField TBDepEmp;
    private javax.swing.JTextField TBIDEmp;
    private javax.swing.JTextField TBNomEmp;
    private javax.swing.JTextField TBSalarEmp;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnModDat;
    private javax.swing.JButton btnMostEmp;
    // End of variables declaration//GEN-END:variables
}
