/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package sistemagestionempleadosform.FuncGerente;

/**
 *
 * @author USUARIO
 */
public class MenuGer extends javax.swing.JFrame {

    /**
     * Creates new form ContEmp
     */
    public MenuGer() {
        initComponents();
        this.setLocationRelativeTo(null);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        seleccion = new javax.swing.JLabel();
        btnContEmp = new javax.swing.JButton();
        btnDespEmp = new javax.swing.JButton();
        btnSalarios = new javax.swing.JButton();
        btnEmpleados = new javax.swing.JButton();
        btnNuevDep = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        seleccion.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        seleccion.setText("Seleccione la acción que desea hacer");

        btnContEmp.setText("Contratar empleado");
        btnContEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnContEmpActionPerformed(evt);
            }
        });

        btnDespEmp.setText("Despedir empleado");
        btnDespEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDespEmpActionPerformed(evt);
            }
        });

        btnSalarios.setText("Salarios departamentos");

        btnEmpleados.setText("Ver empleados");
        btnEmpleados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEmpleadosActionPerformed(evt);
            }
        });

        btnNuevDep.setText("Crear Departamento");
        btnNuevDep.setToolTipText("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(seleccion)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnDespEmp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnContEmp, javax.swing.GroupLayout.DEFAULT_SIZE, 153, Short.MAX_VALUE))
                                .addGap(31, 31, 31)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnSalarios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnNuevDep, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(125, 125, 125)
                        .addComponent(btnEmpleados, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(seleccion)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnContEmp)
                    .addComponent(btnSalarios))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDespEmp)
                    .addComponent(btnNuevDep))
                .addGap(18, 18, 18)
                .addComponent(btnEmpleados)
                .addContainerGap(43, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnContEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnContEmpActionPerformed
        ContEmp Samuel = new ContEmp();
        Samuel.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnContEmpActionPerformed

    private void btnDespEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDespEmpActionPerformed
        DespEmp Alejandro = new DespEmp();
        Alejandro.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnDespEmpActionPerformed

    private void btnEmpleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEmpleadosActionPerformed
        VerEmp Felipe = new VerEmp();
        Felipe.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnEmpleadosActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnContEmp;
    private javax.swing.JButton btnDespEmp;
    private javax.swing.JButton btnEmpleados;
    private javax.swing.JButton btnNuevDep;
    private javax.swing.JButton btnSalarios;
    private javax.swing.JLabel seleccion;
    // End of variables declaration//GEN-END:variables
}
