/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package sistemagestionempleadosform.FuncEmpleado;

/**
 *
 * @author USUARIO
 */
public class MenuEmp extends javax.swing.JFrame {

    /**
     * Creates new form MenuEmp
     */
    public MenuEmp() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BusNomEmp = new javax.swing.JLabel();
        TBEmpNom = new javax.swing.JTextField();
        ShowID = new javax.swing.JLabel();
        ShowSalario = new javax.swing.JLabel();
        ShowDep = new javax.swing.JLabel();
        btnRegresar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        BusNomEmp.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        BusNomEmp.setText("Ingresar nombre de empleado registrado");

        ShowID.setText("ID:");

        ShowSalario.setText("Salario:");

        ShowDep.setText("Departamento");

        btnRegresar.setText("Regresar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnRegresar)
                    .addComponent(ShowDep)
                    .addComponent(ShowSalario)
                    .addComponent(ShowID)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(BusNomEmp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(TBEmpNom)))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(BusNomEmp)
                .addGap(18, 18, 18)
                .addComponent(TBEmpNom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(ShowID)
                .addGap(18, 18, 18)
                .addComponent(ShowSalario)
                .addGap(18, 18, 18)
                .addComponent(ShowDep)
                .addGap(43, 43, 43)
                .addComponent(btnRegresar)
                .addContainerGap(55, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BusNomEmp;
    private javax.swing.JLabel ShowDep;
    private javax.swing.JLabel ShowID;
    private javax.swing.JLabel ShowSalario;
    private javax.swing.JTextField TBEmpNom;
    private javax.swing.JButton btnRegresar;
    // End of variables declaration//GEN-END:variables
}
